name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Update coverage badge
      uses: ncruces/go-coverage-report@v0
